# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    category:
        label: vancoders.news::lang.category.singular
        conditions: category_id in (:filtered)
        modelClass: Vancoders\News\Models\Post
        options: filterCategory

    published_date:
        label: vancoders.news::lang.post.published_at
        type: daterange
        conditions: published_at >= ':after' AND published_at <= ':before'

    status_published:
        label: vancoders.news::lang.post.status_published
        type: checkbox
        conditions: status = 1

    status_hide:
        label: vancoders.news::lang.post.status_hidden
        type: checkbox
        conditions: status = 2

    status_draft:
        label: vancoders.news::lang.post.status_draft
        type: checkbox
        conditions: status = 3

    created_date:
        label: vancoders.news::lang.post.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: vancoders.news::lang.post.updated_at
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
