list: $/vancoders/news/models/post/columns.yaml
modelClass: Vancoders\News\Models\Post
title: Posts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'vancoders/news/posts/update/:id'
filter: config_filter.yaml
